/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ondrejchrastina.javasample;

import com.google.common.collect.Collections2;
import com.kenticocloud.delivery.ContentItemsListingResponse;
import com.kenticocloud.delivery.DeliveryClient;
import com.kenticocloud.delivery.DeliveryParameterBuilder;

import java.util.Collection;
import java.util.Collections;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        DeliveryClient client = new DeliveryClient("4d19ff4c-3274-4282-83e6-56e0e3a492b4");

        ContentItemsListingResponse response = client.getItems(
                DeliveryParameterBuilder.params()
                        .language("en-US")
                        .filterEquals("system.type", "article")
                        .orderByDesc("elements.post_date")
                        .build()
        );

        Collection<String> x = Collections2.transform(
                response.getItems(),
                contentItem -> contentItem.getString("title")
                );

        System.out.println(new App().getGreeting());
    }
}
